### ISSUE TITLE
Images for README.md

### ISSUE THREAD

**Issue by nikw** [SungardAS/snapdirector#13]
![image001](https://cloud.githubusercontent.com/assets/1557544/9996392/c7223fe0-6054-11e5-8f26-d81fd5240840.png)
![image003](https://cloud.githubusercontent.com/assets/1557544/9996391/c7212b5a-6054-11e5-9597-4e0e55e20343.png)
![image005](https://cloud.githubusercontent.com/assets/1557544/9996395/c726f828-6054-11e5-88ef-bbefdce83cd2.png)
![image007](https://cloud.githubusercontent.com/assets/1557544/9996394/c726a210-6054-11e5-968a-f3c989ffd358.png)
![image009](https://cloud.githubusercontent.com/assets/1557544/9996397/c727651a-6054-11e5-8547-bc5b9b69ee98.png)
![image011](https://cloud.githubusercontent.com/assets/1557544/9996393/c72474f4-6054-11e5-817e-16cae42b4a69.png)
![image013](https://cloud.githubusercontent.com/assets/1557544/9996396/c7270c32-6054-11e5-95ff-47632ba834b8.png)
![image015](https://cloud.githubusercontent.com/assets/1557544/9996398/c72d1fb4-6054-11e5-8047-44e2fb2e21ef.png)
![image017](https://cloud.githubusercontent.com/assets/1557544/9996399/c72f2a66-6054-11e5-957a-b71bd33185c9.png)
![image019](https://cloud.githubusercontent.com/assets/1557544/9996402/c731f35e-6054-11e5-945e-dc2a9c9c1d8a.png)
![image021](https://cloud.githubusercontent.com/assets/1557544/9996400/c72f9c4e-6054-11e5-9d6a-2c18a8b07c98.png)
![image023](https://cloud.githubusercontent.com/assets/1557544/9996403/c73286a2-6054-11e5-8f0b-4954bcca8d20.png)
![image025](https://cloud.githubusercontent.com/assets/1557544/9996401/c730deec-6054-11e5-9ae0-ab4576a971d7.png)
![image027](https://cloud.githubusercontent.com/assets/1557544/9996404/c7337b3e-6054-11e5-8e12-5a0c7e139134.png)
![image029](https://cloud.githubusercontent.com/assets/1557544/9996405/c73995aa-6054-11e5-8a14-00ff0120a852.png)
![image031](https://cloud.githubusercontent.com/assets/1557544/9996406/c73a0dfa-6054-11e5-834e-8e8a4c75bd45.png)

**Comment by KostiantynGlukhenko** [comment]
![screen shot 2016-09-21 at 14 53 57](https://cloud.githubusercontent.com/assets/3055547/18709946/524537e0-800b-11e6-8f9b-44bf8147961b.png)
![screen shot 2016-09-21 at 15 00 15](https://cloud.githubusercontent.com/assets/3055547/18710297/295064f2-800d-11e6-8025-334eff8cbb99.png)
![screen shot 2016-09-21 at 15 03 23](https://cloud.githubusercontent.com/assets/3055547/18710301/2d13d448-800d-11e6-98f3-204f69bcdd4f.png)
![screen shot 2016-09-21 at 15 07 14](https://cloud.githubusercontent.com/assets/3055547/18710305/2f3736d4-800d-11e6-863c-2a5096f8385b.png)
